// import { useState, createContext, useContext } from "react";

// const authContext = createContext();

// function AuthProvider({ children }) {
//   const [user, setUser] = useState(null);
//   return (
//     <authContext.Provider value={{ user, login, logout }}>
//       {children}
//     </authContext.Provider>
//   );
// }

// export const useAuth = () => {
//   return useContext(authContext);
// };
